### ISSUE TITLE
Where did I consent to receive email from you?

### ISSUE THREAD

**Issue by phoe** [find-price/interface#2]
Attached is a spam message that I received from `no-reply@findprice.money`. I never registered for your service and I would like to know where you got my email address from and where you got my marketing consent from.

[Find Price For Open Source Project - FindPrice DAO (no-reply@findprice.money) - 2022-02-23 1603.eml.txt](https://github.com/find-price/interface/files/8125577/Find.Price.For.Open.Source.Project.-.FindPrice.DAO.no-reply%40findprice.money.-.2022-02-23.1603.eml.txt)

**Comment by dswu** [comment]
There will not be any new mailings per se, and in the meantime, the project has been suspended
